### ISSUE TITLE
duplicate code

### ISSUE THREAD

**Issue by rickyswang** [AI4Finance-Foundation/ElegantRL#102]
I followed elegantrl half a year ago, it's a good library.
currently there are 3 versions of agent/net/run,  which one to choose? would you please cleanup duplicate code?

**Comment by XiaoYangLiu-FinRL** [comment]
They are designed to be three levels, not duplicate at all.  For Single sever, a sever with multiple GPUs, and even a cluster with hundreds of GPUs.   We release codes developped with over the cost of millions.
