### ISSUE TITLE
uncorrect dimension in my test 

### ISSUE THREAD

**Issue by graceyangfan** [AI4Finance-Foundation/ElegantRL#108]
https://github.com/AI4Finance-Foundation/ElegantRL/blob/fab3220f2e5b2952641ecfbca88ab3ea4fd0cfce/elegantrl/agents/AgentPPO.py#L120
the code sholud be:
`
            (torch.tensor(buf_srdan[1], dtype=torch.float32) * self.reward_scale).unsqueeze(1).unsqueeze(2),
            ((1 - torch.tensor(buf_srdan[2], dtype=torch.float32)) * self.gamma).unsqueeze(1).unsqueeze(2),
`

**Comment by hmomin** [comment]
Hi, thanks for opening this issue.  Could you please post your test code as well?  Just something we can use to verify that this is an error with the library specifically.

Thanks,
Momin

**Comment by hmomin** [comment]
Hey @graceyangfan, if you can show us any error output when running your code and some small script to reproduce the error, I'd be happy to look more into this.

Otherwise, I'll close this issue soon for inactivity.
