### ISSUE TITLE
No module named 'elegantrl' !!!

### ISSUE THREAD

**Issue by ghaffari903** [AI4Finance-Foundation/ElegantRL#119]
![er](https://user-images.githubusercontent.com/97940416/156914191-1c16acf3-9033-45ca-9e56-f852bbfd0da0.png)

**Comment by hmomin** [comment]
Did you install ElegantRL? In other words, did you run the first code-block of this tutorial?

If this fixes the problem, please be sure to close the issue.

![install_eRL](https://user-images.githubusercontent.com/72412509/156927849-4f78ebcd-2ae9-48f5-9250-752007ba8c88.png)

**Comment by ghaffari903** [comment]
Yes I installed, but the new changes on elegantrl is not consistent to imports in finrl document

**Comment by hmomin** [comment]
Thanks, this should be fixed soon. It's directly related to Issue #118...

- Momin

**Comment by hmomin** [comment]
I think this issue should be posted in FinRL, not ElegantRL. No worries, I can post it tomorrow, but @ghaffari903 you've essentially got the fix for it!
