### ISSUE TITLE
ModuleNotFoundError: No module named 'elegantrl.config'

### ISSUE THREAD

**Issue by yizhangliu** [AI4Finance-Foundation/ElegantRL#120]
ModuleNotFoundError: No module named 'elegantrl.config'    when I run tutorial_LunarLanderContinuous_v2.ipynb.

In these examples, there are many inconsistencies.    Please check them carefully.  

Thanks.

**Comment by hmomin** [comment]
Thanks for bringing this to our attention, it should be fixed soon. It's directly related to Issue #118...

- Momin

**Comment by hmomin** [comment]
This has now been fixed in commit 1999dbe.
