### ISSUE TITLE
`update_net` in `run.py`  missing parameters

### ISSUE THREAD

**Issue by jc-bao** [AI4Finance-Foundation/ElegantRL#129]
[`agent.update_net`](https://github.com/AI4Finance-Foundation/ElegantRL/blob/fb35e25f01c50af61fa4697824025be50b2e53f1/elegantrl/agents/AgentPPO.py#L205) need 4 parameters, while [`train_and_evaluate`](https://github.com/AI4Finance-Foundation/ElegantRL/blob/fb35e25f01c50af61fa4697824025be50b2e53f1/elegantrl/train/run.py#L44) only provide one.

**Comment by hmomin** [comment]
> [`agent.update_net`](https://github.com/AI4Finance-Foundation/ElegantRL/blob/fb35e25f01c50af61fa4697824025be50b2e53f1/elegantrl/agents/AgentPPO.py#L205) need 4 parameters, while [`train_and_evaluate`](https://github.com/AI4Finance-Foundation/ElegantRL/blob/fb35e25f01c50af61fa4697824025be50b2e53f1/elegantrl/train/run.py#L44) only provide one. 

There is currently a discrepancy between `AgentPPO` in `elegantrl/agents/agent.py` and `AgentPPO` in `elegantrl/agents/AgentPPO.py`. I would recommend using the implementation in `elegantrl/agents/agent.py` as it's much more stable anyway -> you'll notice that `agent.update_net` in that implementation only takes one parameter, which is the `buffer`.

Someone should really get the two implementations in sync, there's absolutely no reason for them to be different from one another - I would do it myself, but I'm not working that closely with the `agents` folder, so don't want to run into a merge conflict with someone else.

If this is a satisfactory answer, please remember to close the issue.

**Comment by jc-bao** [comment]
Thanks for the information! 
I think it would be better to modify the `tutorial_Isaac_Gym.py` where import `AgentPPO` from `AgentPPO.py`.
