### ISSUE TITLE
gpu_id出现问题

### ISSUE THREAD

**Issue by Syk-yr** [AI4Finance-Foundation/ElegantRL#145]
您好，万分抱歉打扰您。我在自建gym环境以及在使用您提供的“elegantrl/envs/CarRacingFix”环境在使用算法AgentSAC_H时都出现了TypeError: __init__() got an unexpected keyword argument 'gpu_id‘的问题，但我在使用gym提供的官方环境时，如"BipedalWalker-v3"就可以正常运行，想请问是否能帮忙解决此问题。谢谢！我的电脑是单GPU的。
同时还想请教您，AgentSAC和AgentSAC_H的区别？

**Comment by Yonv1943** [comment]
CarRacingFix”环境 需要以图片作为输入，使用 AgentSAC 代码运行这个环境，需要你 修改 actor网络，以及 critic 网络

**Comment by Syk-yr** [comment]
非常谢谢您的回答，同时谢谢您开源了此项目！
