### ISSUE TITLE
ReplayBufferMP有错误

### ISSUE THREAD

**Issue by Syk-yr** [AI4Finance-Foundation/ElegantRL#164]
当我想把PER加入到SAC中时发现作者在以下地方可能存在笔误：elegantrl/train/replay_buffer.py/class ReplayBufferMP{
...
self.buffers = [
            ReplayBuffer(
                max_len=buf_max_len,
                state_dim=state_dim,
                action_dim=action_dim,
       ****if_use_per=if_use_per,******
                gpu_id=gpu_id,
            )
            for _ in range(buffer_num)
        ]
...
}
在buffer的初始化中不包含if_use_per参数，但使用ReplayBufferMP初始化则需要包含buffer_num？

**Comment by Yonv1943** [comment]
你好，很感谢你的issue。我们在 ElegantRL的 dev 分支里，已经修复了这个问题。
等dev分支 合并到 master 主分支后，这些问题将得到解决

https://github.com/AI4Finance-Foundation/ElegantRL/blob/1fadb93eebb7abcfff76679636c9bb0b12170ca4/elegantrl/train/replay_buffer.py#L33-L35


我提议你使用我们 dev 分支的代码

**Comment by Syk-yr** [comment]
谢谢作者的详细解答，万分感谢！！！
