### ISSUE TITLE
ElegantRL/dev/config.py有疑问

### ISSUE THREAD

**Issue by Syk-yr** [AI4Finance-Foundation/ElegantRL#166]
class Arguments:
    def __init__(self, agent_class=None, env=None, env_func=None, env_args: dict = None):
...
 if self.if_off_policy:  # off-policy
...
self.if_off_policy = self.if_off_policy()  # agent is on-policy or off-policy

我看到self.if_off_policy在未申明或赋值的情况下使用

**Comment by Yonv1943** [comment]
`self.if_off_policy = self.if_off_policy() # agent is on-policy or off-policy`

在这一行代码，为 `self.if_off_policy` 值赋值。若检测到算法的名称中含有 A2C 或者 PPO这些 on-policy算法，那它就会自动赋值为 `self.if_off_policy = False`

https://github.com/AI4Finance-Foundation/ElegantRL/blob/1fadb93eebb7abcfff76679636c9bb0b12170ca4/elegantrl/train/config.py#L99-L102

如果是自己定义的算法，那么算法设计者可以自己指定算法的 `self.if_off_policy` 这个布尔值。例如，下面的DDPG算法，我们在写下这个算法的代码时，就自己主动地给它定义了`self.if_off_policy = True`

https://github.com/AI4Finance-Foundation/ElegantRL/blob/1fadb93eebb7abcfff76679636c9bb0b12170ca4/elegantrl/agents/AgentDDPG.py#L30-L31




> class Arguments: def **init**(self, agent_class=None, env=None, env_func=None, env_args: dict = None): ... if self.if_off_policy: # off-policy ... self.if_off_policy = self.if_off_policy() # agent is on-policy or off-policy
> 
> 我看到self.if_off_policy在未申明或赋值的情况下使用

**Comment by Yonv1943** [comment]
> 在config.py的中Arguments包含了两个参数 self.eval_env_func = None # eval_env = eval_env_func(*eval_env_args) self.eval_env_args = None # eval_env = eval_env_func(*eval_env_args) 之后看到类中并为对其进行其他操作
> 
> 在调用Arguments之后，运行train_and_evaluate(args 后运行至evaluator = init_evaluator(args, gpu_id) => eval_func = args.eval_env_func if hasattr(args, "eval_env_func") else args.env_func eval_args = args.eval_env_args if hasattr(args, "eval_env_args") else args.env_args eval_env = build_env(args.env, eval_func, eval_args) init_evaluator中的前两句eval_func，eval_args获得的是None，因此也无法建立环境
> 
> 我不知道我的运行过程是否正确，是否在中间或者前面少了什么函数。在构建Arguments之前我并没有调用get_gym_env_args函数，不知是否与此有关，谢谢解答

与之相关的是函数 `build_env`，在开启多个worker用于并行加速时，我们需要额外地建立一些新的仿真环境。这段代码的逻辑如下：
1. 若使用者提供了 `env` 这个环境，那么它直接对这个环境进行 深拷贝 deepcopy。然而，一些环境无法通过深拷贝的方式创建新环境，所以要有下面这一步
2. 若使用者不提供 `env` 这个环境，而是提供了创建这个环境的 `env_func=gym.make`和 `env_args=env_name`，那么代码将直接用gym去创建已经注册好了的环境。
3. 若使用者不提供 `env` 这个环境，而是提供了创建这个环境的 `env_func`和 `env_args`，那么我们就能用更加不容易报错的方法创建环境了，也就是 `env = env_func(**env_args)`

https://github.com/AI4Finance-Foundation/ElegantRL/blob/1fadb93eebb7abcfff76679636c9bb0b12170ca4/elegantrl/train/config.py#L206-L216

为什么代码中有：
- `env`
- `env_func`
- `env_args`
还会有带 `eval` 前缀的env相关变量呢？ 因为一些任务的用于探索的环境 `env` 相当于 训练集，所以需要有评估环境 `eval_env` 作为测试集，因此还有：
- `eval_env`
- `eval_env_func`
- `eval_env_args`

有使用测试集 `eval_env` 这个需求的用户，可以自己指定 `eval_env`。使用方法也比较简单，就是：
```
args.env_func = xxx1
args.env_args = {xx:xxx, xxx:xxx}

args.eval_env_func = xxx2
args.eval_env_args = {xx:xxx, xxx:xxx}
```

没有使用 `eval_env` 需求的用户，就不需要进行相关设置了，因为它会自动设置成 `env`：
https://github.com/AI4Finance-Foundation/ElegantRL/blob/1fadb93eebb7abcfff76679636c9bb0b12170ca4/elegantrl/train/run.py#L108-L111

**Comment by Syk-yr** [comment]
谢谢作者的详细解答，万分感谢！！！
