### ISSUE TITLE
Fail to run tutorial_Isaac_Gym.py

### ISSUE THREAD

**Issue by planetbalileua** [AI4Finance-Foundation/ElegantRL#169]
Hello! Thank you for creating this brilliant library! This is so helpful on a personal project I am working on.
I faced an error when trying to run tutorial_Isaac_Gym.py in the example folder:
<pre>Traceback (most recent call last):
  File &quot;/home/meow/anaconda3/envs/igym/lib/python3.8/multiprocessing/process.py&quot;, line 315, in _bootstrap
    self.run()
  File &quot;/home/meow/anaconda3/envs/igym/lib/python3.8/multiprocessing/process.py&quot;, line 108, in run
    self._target(*self._args, **self._kwargs)
  File &quot;/home/meow/ElegantRL/elegantrl/train/run.py&quot;, line 162, in run
    env = build_env(args.env, args.env_func, args.env_args)
  File &quot;/home/meow/ElegantRL/elegantrl/train/config.py&quot;, line 249, in build_env
    env = env_func(**kwargs_filter(env_func.__init__, env_args.copy()))
  File &quot;/home/meow/ElegantRL/elegantrl/envs/IsaacGym.py&quot;, line 45, in __init__
    env: VecTask = isaac_task(
  File &quot;/home/meow/ElegantRL/elegantrl/envs/isaac_tasks/ant.py&quot;, line 69, in __init__
    super().__init__(
  File &quot;/home/meow/ElegantRL/elegantrl/envs/isaac_tasks/base/vec_task.py&quot;, line 213, in __init__
    self.create_sim()
  File &quot;/home/meow/ElegantRL/elegantrl/envs/isaac_tasks/ant.py&quot;, line 156, in create_sim
    self._create_envs(
  File &quot;/home/meow/ElegantRL/elegantrl/envs/isaac_tasks/ant.py&quot;, line 199, in _create_envs
    self.joint_gears = to_torch(motor_efforts, device=self.device)
  File &quot;/home/meow/Downloads/IsaacGym_Preview_3_Package/isaacgym/python/isaacgym/torch_utils.py&quot;, line 16, in to_torch
    return torch.tensor(x, dtype=dtype, device=device, requires_grad=requires_grad)
  File &quot;/home/meow/anaconda3/envs/igym/lib/python3.8/site-packages/torch/cuda/__init__.py&quot;, line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: out of memory
</pre>

I'm running this on NVIDIA RTX3070TI with 8GB VRAM, and my  CUDA version is:
<pre>$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
</pre>

The same Ant(with 2048env) example was working when I test it using the original isaac gym train.py. I'm pretty sure that I have free VRAM (~7.2GB) when running this but it still appears the CUDA out of memory error. My torch version is 1.11.0.

I have also tried to reduce the number of envs, batch size, network size and other parameters, but the error remains.

Once again thank you so much for any possible help on this issue

**Comment by supersglzc** [comment]
Hi planetbalileua and thanks for reaching out! 

We realize that some codes are not consistent due to the fast iteration and we are doing refactorings. 
For Isaac Gym users, I have published a single process version with a [demo](https://github.com/AI4Finance-Foundation/ElegantRL/blob/IsaacGym-Single-Process/demo_IsaacGym.py) on Ant and Humanoid. Could you please try that and see if the error remains?

**Comment by planetbalileua** [comment]
Hi!
I have tested the updated file and there's an error on finding train_and_evaluate_mp in run.py for the latest release.
Some other errors from my side:
<pre>ImportError: cannot import name &apos;ReplayBufferList&apos; from &apos;elegantrl.train.replay_buffer&apos; (/home/meow/ElegantRL/elegantrl/train/replay_buffer.py)
</pre>
So I added replay buffer list in replay_buffer.py

<pre>  File &quot;/home/meow/ElegantRL/elegantrl/agents/AgentPPO.py&quot;, line 657, in AgentPPOHterm
    def __init__(self, net_dim: int, state_dim: int, action_dim: int, gpu_id: int = 0, args: Arguments = None):
NameError: name &apos;Arguments&apos; is not defined
</pre>
Added from elegantrl.train.config import Arguments

Thank you again for updating!

**Comment by supersglzc** [comment]
Fixed the errors. The issue is closed.
