### ISSUE TITLE
how to continue training an agent after stopping (paused)?

### ISSUE THREAD

**Issue by ulstaer** [AI4Finance-Foundation/ElegantRL#17]
the function " train_and_evaluate__multiprocessing(args) ", when restarted, erases all previous learning process.

Param "args.if_remove = False" - Does not help
Func "agent.save_load_model( )" - Does not help

Maybe added - train_and_evaluate__multiprocessing(args, if_continue=True, start_weight = 'old_save_weight.pth')?

**Comment by Yonv1943** [comment]
> continue training an agent after stopping

It is easy to implement this function in single processing.
But it is a little complicated in multiple processing.

We will try our best to implement this function.

**Comment by Yonv1943** [comment]
**Congratulations, your wish has come true**. Now you can use this function as follows:
- start training
- **create a file named `stop`** in the cwd (current working directory), then the training will stop
- **set `args.if_remove = False`,** to keep the history file (network parameters, optimizer parameters, replay buffer). Then ElegantRL will load the history files and restart training.


---

We have fully upgraded ElegantRL and now supports multiple GPU training (1~8 GPU). 

**Now the problem you mentioned has been resolved**. I'm sorry that we have been busy developing the 80 GPU version (Cloud platform) of ElegantRL, and we were unable to reply to you in time.

I will close this question in 3 days.
