### ISSUE TITLE
Bug:Merge branch 'dev2' too much fails

### ISSUE THREAD

**Issue by dubodog** [AI4Finance-Foundation/ElegantRL#173]
(https://github.com/AI4Finance-Foundation/ElegantRL/tree/master/elegantrl/agents)/__init__.py

`<<<<<<< HEAD`
from elegantrl.agents.AgentSAC import AgentSAC, AgentModSAC
from elegantrl.agents.AgentREDQ import AgentREDQ
`=======`
from elegantrl.agents.AgentSAC import AgentSAC, AgentReSAC
from elegantrl.agents.AgentSAC import AgentReSACHtermK

`# on-policy`
from elegantrl.agents.AgentA2C import AgentA2C, AgentDiscreteA2C
from elegantrl.agents.AgentPPO import AgentPPO, AgentDiscretePPO
from elegantrl.agents.AgentPPO import AgentPPOHtermK
`>>>>>>> dev2`

**Comment by shixun404** [comment]
We have fixed this bug.
