### ISSUE TITLE
Bug:convert_trajectory function deleted?

### ISSUE THREAD

**Issue by dubodog** [AI4Finance-Foundation/ElegantRL#174]
[elegantrl](https://github.com/AI4Finance-Foundation/ElegantRL/tree/master/elegantrl)/[agents](https://github.com/AI4Finance-Foundation/ElegantRL/tree/master/elegantrl/agents)/AgentBase.py
`107        return self.convert_trajectory(traj_list, last_dones)`
[elegantrl](https://github.com/AI4Finance-Foundation/ElegantRL/tree/master/elegantrl)/[agents](https://github.com/AI4Finance-Foundation/ElegantRL/tree/master/elegantrl/agents)/AgentPPO.py
`46 return self.convert_trajectory(traj_list, last_dones)`

the function convert_trajectory is deleted,May be the commit [Refactor](https://github.com/AI4Finance-Foundation/ElegantRL/commit/79e3e8ea196a674ca7962399b3e8ef8cd41e9a8a) has more bugs

**Comment by shixun404** [comment]
We have recovered the old version of AgentPPO. This bug has been fixed.
