### ISSUE TITLE
'Arguments' object has no attribute 'save_gap' 

### ISSUE THREAD

**Issue by AlphonsoCzy** [AI4Finance-Foundation/ElegantRL#182]
This is an error when I try to run the file ' demo_A2C_PPO.py' in examples.
AttributeError: 'Arguments' object has no attribute 'save_gap' and 
AttributeError: 'AgentPPO' object has no attribute 'traj_list'

**Comment by shixun404** [comment]
Thanks a lot for your feedback. I modified the question related to 'traj_list'.  The file ' demo_A2C_PPO.py '  and ' demo_PPO_H.py ' could run correctly now!
