### ISSUE TITLE
有关GAE计算的问题

### ISSUE THREAD

**Issue by luo-li-ba-suo** [AI4Finance-Foundation/ElegantRL#183]
在elegant RL去年的时候，拉取了分支下来，其中PPO的GAE实现方式为：

    @staticmethod
    def get_reward_sum_gae(self, buf_len, buf_reward, buf_mask, buf_value, rest_r_sum) -> (torch.Tensor, torch.Tensor):
        buf_r_sum = torch.empty(buf_len, dtype=torch.float32, device=self.device)  # old policy value
        buf_advantage = torch.empty(buf_len, dtype=torch.float32, device=self.device)  # advantage value

        pre_advantage = rest_r_sum  # advantage value of previous step
        for i in range(buf_len - 1, -1, -1):
            buf_r_sum[i] = buf_reward[i] + buf_mask[i] * rest_r_sum
            rest_r_sum = buf_r_sum[i]

            buf_advantage[i] = buf_reward[i] + buf_mask[i] * (pre_advantage - buf_value[i])  # fix a bug here
            pre_advantage = buf_value[i] + buf_advantage[i] * self.lambda_gae_adv
        buf_advantage = (buf_advantage - buf_advantage.mean()) / (buf_advantage.std() + 1e-5)
        return buf_r_sum, buf_advantage

可以看到有一行注释了 # fix a bug here
按照正确的GAE计算这一行应该改为buf_advantage[i] = buf_reward[i] + buf_mask[i] * pre_advantage - buf_value[i]
但我修改之后，经过大量的实验发现，训练效果居然不如修改前，奖励爬升的会更慢

如今再回到elegantRL最新的PPO实现中，发现GAE的这个计算问题早已修复。请问作者们对这个问题的考量是怎样的呀，当时应该也是发现这个bug可以促进训练所以才没改吧，但是为什么后来还是修正了呢，我很好奇这之间发生了什么，跪求大佬请教一二

**Comment by Yonv1943** [comment]
谢谢你的关注，我们多多交流，相关考量如下：
```
# 去年的
buf_advantage[i] = buf_reward[i] + buf_mask[i] * (pre_advantage - buf_value[i])  # fix a bug here 
buf_advantage[i] = buf_reward[i] + buf_mask[i] * pre_advantage - buf_mask[i] * buf_value[i]  # 换另一种写法

# 今年的，按照正确的GAE计算
buf_advantage[i] = buf_reward[i] + buf_mask[i] * pre_advantage - buf_value[i]

# 其中t时刻的 buf_mask = (1-done) * gamma

```

为了方便讨论，我们暂时将这两个方案称为“去年版” 和 “今年版”。

两个版本的区别在于 去年版是 `buf_value[i] * buf_mask[i] == buf_value[i] * (1-done) * gamma`，今年版是 `buf_value[i]`

## 区别1
区别：在终止时刻，有`1-done==0`，那么在终止时刻的reward值 不为0 的情况下，去年版有`buf_value[i] * (1-done) * gamma==-0`，而今年版的计算不为0。从而，在终止时刻上，去年版算出的 advantage value 的绝对值将比 今年版的，更接近于非终止时刻的 advantage value 均值。

影响：单从优势值的计算看，它们的区别在于终止状态的reward要不要算作优势。去年版把终止状态的reward用mask掩盖掉了，认为终止状态没法做出动作，所以自然没有因为做出恰当动作而带来的“优势”。

## 区别2
区别：在非终止时刻，去年版有`pre_advantage * gamma - buf_value[i] * gamma`，今年版有`pre_advantage * gamma - buf_value[i]`，可以看到区别在于是否给 value 多乘以一个折扣因子gamma。

影响：今年版相当于用正确的方法计算，有`buf_advantage = buf_r_sum - buf_value`，去年版相当于用这样计算 → `buf_advantage = buf_r_sum - buf_value * gamma`（没有带来很大影响，是因为 gamma=0.99 与1.0 差别很小，但终归在数学上是不正确的）

## 总结
实现算法时，如果有比作者更好的实现（指：在一些基准任务上暂时观察到改动带来的明显提升），那么：
- **假如在数学上，完全没有修改作者的算法，只是在代码上的改进**，那么我们可以直接把改动更新到算法里（例如SAC计算策略熵的时候，因为浮点数精度极限的缘故，我们把 `1-tanh(x)**2` 改成了 `soft_plus(noise-2)`，我们就直接把这个改动写到SAC算法的实现里
- **假如在数学上，改动了作者的算法**。例如，去年版的GAE已经把作者的公式改变了，尽管它在一些任务上观察到提升，但是这不适合。因此今年我们又把它改回来了。倘若去年版的改动真的非常好，在大量任务上观察到提升，那也最好重新写一个 GAE的计算函数，告诉使用者“这与作者发表过的论文的算法有不同，且不同在于某某处”，而不能像去年版一样直接告诉大家说：“这就是GAE”



> 因为浮点数精度极限的缘故，我们把 `1-tanh(x)**2` 改成了 `soft_plus(noise-2)`，详见以下
https://github.com/AI4Finance-Foundation/ElegantRL/blob/114162d57b5d3b407a9d9427a61fa951277dd5be/elegantrl/agents/net.py#L345-L360

**Comment by luo-li-ba-suo** [comment]
感谢您的详细分析和耐心回复！！！令人醍醐灌顶！
仔细考虑了一下，我对区别一的理解是，在很多任务中，终止状态（done为True时的next_state）可以分为真实终止状态和伪终止状态两种情况分析，真实终止状态比如游戏胜负已定，伪终止状态是单局时间限制截断，前者的状态价值是0没有错，后者的状态价值则不应该为0。
那么在去年的实现中，针对伪终止状态，buf_reward[i] + buf_mask[i] * (pre_advantage - buf_value[i])比buf_reward[i] + 0 - buf_value[i]更接近真实的优势值buf_reward[i] + buf_mask[i] * buf_value[i+1]- buf_value[i].

这么一来解决办法就出来了，针对伪终止状态再设置一个不同的done就好了；但可能并不适用于任意任务

**Comment by luo-li-ba-suo** [comment]
但是在真实终止状态下，去年的实现反而不够准确
所以感觉在伪终止状态比真实终止状态更多的任务场景下，去年的实现会比今年的实现更好

**Comment by XiaoYangLiu-FinRL** [comment]
Any update regarding this issue?  If it is fixed, can we close it?
