### ISSUE TITLE
Duplicate methods in AgentBase.py

### ISSUE THREAD

**Issue by jimmydengpeng** [AI4Finance-Foundation/ElegantRL#208]
Duplicate method:
```python
def save_or_load_agent(self, cwd: str, if_save: bool):
```
of `line 247` and `line 344`
in `elegantrl/agents/AgentBase.py`.

**Comment by shixun404** [comment]
Thanks for your reminder! The duplicated method has been removed by https://github.com/AI4Finance-Foundation/ElegantRL/pull/209.
