### ISSUE TITLE
Duplicate class in replay_buffer.py

### ISSUE THREAD

**Issue by jimmydengpeng** [AI4Finance-Foundation/ElegantRL#215]
There are two classes with same name `ReplayBufferList` within file
`elegantrl / train / replay_buffer.py` 
in line `275` and `309`.

They contain same named methods, but slightly differ in contents. However, the latter one will be used in runtime. 

Which one is correct or expected?

**Comment by shixun404** [comment]
@jimmydengpeng  Thanks for your reminder! The duplicated class has been fixed in [Pull Request #219](https://github.com/AI4Finance-Foundation/ElegantRL/pull/219#issue-1376665184). Please let us know if you have any feedback or suggestions :)
