### ISSUE TITLE
Cannot find reference 'ActorMAPPO' in 'net.py' 

### ISSUE THREAD

**Issue by josyulakrishna** [AI4Finance-Foundation/ElegantRL#230]
Hi I want to use this library for Multiagent RL, in `AgentMAPPO.py` file there are two undefined references 
`from elegantrl.agents.net import ActorMAPPO, CriticMAPPO`  `ActorMAPPO` and `CriticMAPPO` how can I fix can this?

**Comment by shixun404** [comment]
@josyulakrishna Hi, there is an available demo for QMIX  in a past version of ElegantRL, https://github.com/AI4Finance-Foundation/ElegantRL/commit/02dd28aa25fce9db2a663dfa5d3052551bd83561. 
* You can check out the version by running the following command
```
git checkout 02dd28
```
* This demo tests the QMIX algorithm on SMAC tasks. You can install SMAC by following the instructions at https://github.com/AI4Finance-Foundation/ElegantRL/blob/02dd28aa25fce9db2a663dfa5d3052551bd83561/elegantrl/envs/starcraft/README.md
* Run the following command to test QMIX
```
python3 elegantrl/Demo_SMAC.py --config=qmix --env-config=sc2 with env_args.map_name=corridor
```

Thanks for your participation :) For MAPPO, our team will deliver it as soon as possible.

**Comment by josyulakrishna** [comment]
@shixun404  thank you very much, i will use this right away, can i use QMIX for continuous action spaces?

**Comment by shixun404** [comment]
@josyulakrishna No problem. This QMIX demo is for discrete action space. For continuous action space, you can use MADDPG or MAPPO. I thought there was a MADDPG demo before. I will go to check it :)

**Comment by josyulakrishna** [comment]
Thank you! My application is on continuous action spaces, if the maddpg demo is available too that'd be great, apologies for too many requests haha..

**Comment by shixun404** [comment]
@josyulakrishna Take it easy :) This is a MADDPG demo https://github.com/shixun404/MADDPG_Demo. Thanks for your interest in ElegantRL.

**Comment by josyulakrishna** [comment]
Haha thank you again! :)

**Comment by shixun404** [comment]
@josyulakrishna You're welcome! Thanks for your support of ElegantRL.
