### ISSUE TITLE
Request for some examples with RLlib and IsaacGym

### ISSUE THREAD

**Issue by Skylark0924** [AI4Finance-Foundation/ElegantRL#236]
Hi guys,

Thank you so much for the ElegantRL package and your ongoing efforts to integrate Isaac Gym.

I noticed that you have already [compared the performance between ElegantRL and RLlib by using Isaac Gym](https://github.com/AI4Finance-Foundation/ElegantRL/blob/master/docs/source/tutorial/isaacgym.rst). I am wondering whether you could provide some extra examples about using RLlib in the IsaacGym (cause I'm working on and also got stuck by this).

Many thanks!

**Comment by Yonv1943** [comment]
We use [RLlib==0.8.6](https://docs.ray.io/en/releases-0.8.6/) to train on Isaac Gym env, which is easier to train on a custom env than [RLlib==1.13](https://docs.ray.io/en/releases-1.13.0/).

You can download all the files in this folder. We use this environment (Isaac Gym Previous 3) for RLlib.
https://github.com/AI4Finance-Foundation/ElegantRL/tree/IsaacGym-Single-Process/elegantrl/envs

**Comment by Skylark0924** [comment]
Thanks a lot!!!!

**Comment by Skylark0924** [comment]
Sorry to bother you again. I have tried the Ray version you mentioned and the envs you provided, it works if I just set a single env for isaacgym and num_workers=0 for rllib. However, if I increase the number of envs, and try to use the [Vector Env](https://docs.ray.io/en/latest/rllib/package_ref/env/vector_env.html#) Ray provided, it will crash.  I think the idea behind the Vector Env of rllib is conflicted with isaacgym. I wonder if you could you give me more advice about the rllib env wrapper? Many thanks!!!

**Comment by Skylark0924** [comment]
Already achieved connecting Isaac Gym with RLlib by https://github.com/Skylark0924/Rofunc/issues/30, but still hope there will be additional examples to verify the correctness of my code.
