### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'action_dim'

### ISSUE THREAD

**Issue by haisheng666** [AI4Finance-Foundation/ElegantRL#237]
If you run your own example, errors will be reported. Please help us to find out what the problem is?

/opt/anaconda3/envs/elegant_RL/bin/python /home/lhs/PycharmProjects/elegant_RL/tutorial_BipedalWalker-v3.py 
WARNING: env.action_space.high [1. 1. 1. 1.]
env_args = {
    'env_num': 1,
    'env_name': 'BipedalWalker-v3',
    'max_step': 1600,
    'state_dim': 24,
    'action_dim': 4,
    'if_discrete': False,
    'target_return': 300,
}
| Arguments Remove cwd: ./BipedalWalker-v3_PPO_0
Traceback (most recent call last):
  File "/home/lhs/PycharmProjects/elegant_RL/tutorial_BipedalWalker-v3.py", line 32, in <module>
    train_and_evaluate(args)
  File "/opt/anaconda3/envs/elegant_RL/lib/python3.8/site-packages/elegantrl/train/run.py", line 87, in train_and_evaluate
    agent = init_agent(args, gpu_id, env)
  File "/opt/anaconda3/envs/elegant_RL/lib/python3.8/site-packages/elegantrl/train/run.py", line 16, in init_agent
    agent = args.agent_class(args.net_dim, args.state_dim, args.action_dim, gpu_id=gpu_id, args=args)
  File "/opt/anaconda3/envs/elegant_RL/lib/python3.8/site-packages/elegantrl/agents/AgentPPO.py", line 38, in __init__
    AgentBase.__init__(self, net_dim, state_dim, action_dim, gpu_id, args)
  File "/opt/anaconda3/envs/elegant_RL/lib/python3.8/site-packages/elegantrl/agents/AgentBase.py", line 53, in __init__
    self.act = act_class(net_dim, state_dim, action_dim).to(self.device)
TypeError: __init__() missing 1 required positional argument: 'action_dim'

**Comment by Yonv1943** [comment]
The code in `net.py` is 
https://github.com/AI4Finance-Foundation/ElegantRL/blob/f0f518e8412eca961d83c60f80c54f6d45946d8f/elegantrl/agents/net.py#L381

The code in `AgentBase.py` is 
https://github.com/AI4Finance-Foundation/ElegantRL/blob/f0f518e8412eca961d83c60f80c54f6d45946d8f/elegantrl/agents/AgentBase.py#L53

The code in `AgentBase.py` should be:
```
        self.act = act_class(net_dim, num_layers, state_dim, action_dim).to(self.device)
        self.cri = cri_class(net_dim, num_layers, state_dim, action_dim).to(self.device) \
```

I will upload a Pull Request to fix this bug. Thank you.

**Comment by Praying** [comment]
same question, please fix it and merge to master as  soon as possible

**Comment by JonathanLehner** [comment]
self.act = act_class(net_dim, state_dim, action_dim).to(self.device)
        self.cri = cri_class(net_dim, state_dim, action_dim).to(self.device) \
            if cri_class else self.act

this is still in the latest code. It still crashes for me

**Comment by JonathanLehner** [comment]
easy to reproduce by running the sample notebook https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/3-Practical/FinRL_MultiCrypto_Trading.ipynb
