### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by aevfly** [AI4Finance-Foundation/ElegantRL#259]
In this section:

train(start_date=TRAIN_START_DATE, 
      end_date=TRAIN_END_DATE,
      ticker_list=TICKER_LIST, 
      data_source='binance',
      time_interval='5m', 
      technical_indicator_list=INDICATORS,
      drl_lib='elegantrl', 
      env=env, 
      model_name='ppo', 
      current_working_dir='./test_ppo',
      erl_params=ERL_PARAMS,
      break_step=5e4,
      if_vix=False
      )

**Got TypeError: 'NoneType' object does not support item assignment**
Whats wrong ?

Log: 

binance successfully connected
tech_indicator_list:  ['macd', 'rsi', 'cci', 'dx']
indicator:  macd
indicator:  rsi
indicator:  cci
indicator:  dx
Succesfully add technical indicators
Successfully transformed into array
model_name -   ppo
env -   <__main__.CryptoEnv object at 0x7f75f98df340>
| Arguments Remove cwd: ./test_ppo
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-7-c3f95f8e0ccd>](https://localhost:8080/#) in <module>
----> 1 train(start_date=TRAIN_START_DATE, 
      2       end_date=TRAIN_END_DATE,
      3       ticker_list=TICKER_LIST,
      4       data_source='binance',
      5       time_interval='5m',

3 frames
[<ipython-input-3-c2f4f1f1ce9a>](https://localhost:8080/#) in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     35         model = agent.get_model(model_name, model_kwargs = erl_params)
     36 
---> 37         trained_model = agent.train_model(model=model, 
     38                                           cwd=current_working_dir,
     39                                           total_timesteps=break_step)

[/FinRL-Meta/agents/elegantrl_models.py](https://localhost:8080/#) in train_model(self, model, cwd, total_timesteps)
     80         model.break_step = total_timesteps
     81         #train_and_evaluate(model)
---> 82         train_agent(model)
     83 
     84     @staticmethod

[/usr/local/lib/python3.8/dist-packages/elegantrl/train/run.py](https://localhost:8080/#) in train_agent(args)
     26 
     27     '''init environment'''
---> 28     env = build_env(args.env_class, args.env_args, args.gpu_id)
     29 
     30     '''init agent'''

[/usr/local/lib/python3.8/dist-packages/elegantrl/train/config.py](https://localhost:8080/#) in build_env(env_class, env_args, gpu_id)
    111 
    112 def build_env(env_class=None, env_args: dict = None, gpu_id: int = -1):
--> 113     env_args['gpu_id'] = gpu_id  # set gpu_id for vectorized env before build it
    114 
    115     if env_args.get('if_build_vec_env'):

TypeError: 'NoneType' object does not support item assignment

**Comment by Yonv1943** [comment]
Function `build_env()` need an argument `gpu_id` for buliding a vectorized env.

To make it compatible with older versions (single env), I tried to make it automatically get the `gpu_id`.

**Comment by aevfly** [comment]
I tried assign manually 0 or -1 , but this didn't helped. I also try commented this, and got the same error on next line 
if env_args.get('if_build_vec_env'):

so seems like env_args didnt initialized and nothing have, 

also in line
else:
        env = env_class(**kwargs_filter(env_class.__init__, env_args.copy()))

env_args does not have any methods copy

**Comment by aevfly** [comment]
I have resolved this issue by add args_env in def get_model

 env_args = {
            "config": env_config,
            "env_name": env.env_name,
            "state_dim": env.state_dim,
            "action_dim": env.action_dim,
            "if_discrete": False}
