### ISSUE TITLE
SACActor, log(pi)取值

### ISSUE THREAD

**Issue by caozx1110** [AI4Finance-Foundation/ElegantRL#308]
https://github.com/AI4Finance-Foundation/ElegantRL/blob/b974a806e6235f59055c954418e54640fa549331/elegantrl/agents/net.py#L247

这里是不是应该为：
```
logprob = dist.log_prob(action)
```
包括下面的：
https://github.com/AI4Finance-Foundation/ElegantRL/blob/b974a806e6235f59055c954418e54640fa549331/elegantrl/agents/net.py#L266

**Comment by Yonv1943** [comment]
好的，我可以检查一下。

这里是所有 a_avg 这个随机动作的分布的均值，而不使用 action 这个从随机动作采样后得到的动作，使用 a_avg 是为了 重chong采样 的计算。

**Comment by caozx1110** [comment]
好的 谢谢，可能是我的理解有误
