### ISSUE TITLE
multiple trading condition 

### ISSUE THREAD

**Issue by algopy** [AI4Finance-Foundation/ElegantRL#32]
How to set multiple trading condition like Candlestick pattern, RSI,Pivots as a input to choose the trend reversal & continuation for "higher Risk to reward entry"?Only close value is used as input in your setup.

**Comment by Yonv1943** [comment]
I don't know much about finance tasks, but I know that members of my team are developing [AI4Finance-Foundation/NeoFinRL](https://github.com/AI4Finance-Foundation/NeoFinRL) based on [AI4Finance-Foundation/FinRL](https://github.com/AI4Finance-Foundation/FinRL). 

I'll help you ask the next day. (If i remember)

I'm sorry that we have been busy developing the 80 GPU version (Cloud platform) of ElegantRL, and we were unable to reply to you in time.
