### ISSUE TITLE
H-term implementation?

### ISSUE THREAD

**Issue by ugurbolat** [AI4Finance-Foundation/ElegantRL#321]
Hi @XiaoYangLiu-FinRL 

I found the idea of introducing the H-term into RL interesting.

I have read the [H-term paper](https://tensorworkshop.github.io/NeurIPS2020/accepted_papers/NIPS_2020_Workshop_Yiming%20(1).pdf) and [H-term documentation](https://elegantrl.readthedocs.io/en/latest/tutorial/hterm.html#a-simple-add-on). Also realized that there was at some point a [PR](https://github.com/AI4Finance-Foundation/ElegantRL/pull/152). However, I cannot find it in the main branch. I was wondering if will there be any follow-up on this work?

Best,
Ugur

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks for your interests.  We have been actively using it in our current projects,  not releasing The codes yet. 
Some codes are put in this repo, https://github.com/AI4Finance-Foundation/ElegantRL_Solver

**Comment by ugurbolat** [comment]
Thanks a lot. Will look into it!
