### ISSUE TITLE
env is not defined at the last line of eRL_demo_StockTrading.ipynb

### ISSUE THREAD

**Issue by wmmxk** [AI4Finance-Foundation/ElegantRL#35]
I was running eRL_demo_StockTrading.ipynb. Everything is fine except at the end, it complained "env" is not defined. Do you have any ideas how to fix this?

**Comment by dwaynepaschall** [comment]
I can confirm the same code error.

**Comment by dwaynepaschall** [comment]
Looks like the issue may gave been resolved in this pull request: Fix graph processing issue #34
