### ISSUE TITLE
cannot import elegantrl.tutorial.run.train_and_evaluate_mp

### ISSUE THREAD

**Issue by JatGwingLam** [AI4Finance-Foundation/ElegantRL#38]
Hi,

When tried the multiprocess training with train_and_evaluate_mp in elegantrl.tutorial.run, it can't import properly. 

_Python 3.8.0 (default, Feb 25 2021, 22:10:10) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

\>>> from elegantrl.tutorial.run import Arguments, train_and_evaluate

\>>> from elegantrl.tutorial.run import train_and_evaluate_mp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'train_and_evaluate_mp' from 'elegantrl.tutorial.run' (/home/user/elegantrl/ElegantRL/elegantrl/tutorial/run.py)
\>>>_ 

Could you help to fix it?

**Comment by Yonv1943** [comment]
We have fully upgraded ElegantRL and now supports multiple GPU training (1~8 GPU). 

**Now the problem you mentioned has been resolved**. I'm sorry that we have been busy developing the 80 GPU version (Cloud platform) of ElegantRL, and we were unable to reply to you in time.

I will close this question in 3 days.
