### ISSUE TITLE
eRL_demo_StockTrading file error at train_and_evaluate_mp function

### ISSUE THREAD

**Issue by gromob** [AI4Finance-Foundation/ElegantRL#39]
When I execute the commandline "train_and_evalutate_mp(args)" I get the error:

RuntimeError: cuda runtime error (801) : operation not supported at ..\torch/csrc/generic/StorageSharing.cpp:258

and comments on google says "we cannot use multiprocessing CUDA on Windows"
Do I need linux for this?

**Comment by Yonv1943** [comment]
Linux/ MacOS: Python 3.7+ (3.8+ is better)
WinOS: Python 3.9+ (may solve this problem)
