### ISSUE TITLE
A2C

### ISSUE THREAD

**Issue by datctbk** [AI4Finance-Foundation/ElegantRL#50]
Hi! Could I ask if A2C is implemented in EleganRL?

**Comment by augustyno** [comment]
Yes, AC2  is implemented in ElegantRL. So far I did not test it. I just
have played with FINRL single and multi-stock programs.  Do you know how to
train  trained model? i.e, suppose that I trained the model using AAPL
data. Then I saved the model.
I would like to open the model and continue to train the model using let
say XOM data.
 Do you know how to do it?
Thanks,
Augustyn

**Comment by datctbk** [comment]
Thank you for your reply. 
I have check and I could not see that A2C agent.
Could you please tell me which Agent class is A2C?

I think you use save_or_load_agent method that is implemented.
save_or_load_agent(True) for save
save_or_load_agent(False) for load

so if you continue to train, just load model (save_or_load_agent(False)) and continue to train
Thanks
Dat Tran

**Comment by augustyno** [comment]
Dan,

To execute AC2 model  you should execute the following code:

agent = DRLAgent(env = env_train)

A2C_PARAMS = {"n_steps": 5, "ent_coef": 0.005, "learning_rate": 0.0002}

model_a2c = agent.get_model(model_name="a2c",model_kwargs = A2C_PARAMS)

trained_a2c = agent.train_model(model=model_a2c,
tb_log_name='a2c',
total_timesteps=50000)

You of course change parameters values in the above code. For example, you
can increase
total_timesteps to 1000000.
Yes, we can save the model and then load it back. But when I changed the
number of total
steps I got an error.

**Comment by Yonv1943** [comment]
> Hi! Could I ask if A2C is implemented in EleganRL?

**There are NOT A2C/TRPO implemented in ElegantRL.**
In most instances, I think PPO is much better than A2C/TRPO, 
so we **only implemented A2C and TRPO in the local version**, but did not update to github. 

Considering that some people need to use A2C and TRPO algorithms for academic research purposes, 
we will add these algorithms to ElegantRL  after we finish the work at hand.
