### ISSUE TITLE
unexpected keyword argument 'if_on_policy' in eRL_demo_StockTrading Part 5

### ISSUE THREAD

**Issue by franklo79** [AI4Finance-Foundation/ElegantRL#58]
Hi, I just discovered elegance RL and I am testing the jupyter notebooks.
When I run part 5 on eRL_demo_StockTrading, jupyter throws me: 

TypeError: __init__() got an unexpected keyword argument 'if_on_policy'

Looking a bit at the _run.py_ code in _tutorial folder_, I see 

`class Arguments:
    def __init__(self, agent=None, env=None, if_on_policy=False):`

And I have seen that the Arguments class has been updated and now it does not have "if_on_policy" nor "None" as default:

`class Arguments:  # [ElegantRL.2021.10.21]
    def __init__(self, env, agent):`
 
I'm trying to get the code to work but all I'm doing is skipping necessary parts and doesn't work for me.

I'm missing something?

**Comment by lucasdearaujocruz** [comment]
I had the same problem. First define your env and agent, then pass to class creator. You can set the agent's 'if_off_policy' attribute.

```
env = StockTradingEnv(folder_path, gamma, max_stock, initial_capital, buy_cost_pct, 
                                      sell_cost_pct, start_date, start_eval_date, 
                                      end_eval_date, tickers, tech_indicator_list, 
                                      initial_stocks, if_eval=False)

env_eval = StockTradingEnv(folder_path, gamma, max_stock, initial_capital, buy_cost_pct, 
                                             sell_cost_pct, start_date, start_eval_date, 
                                             end_eval_date, tickers, tech_indicator_list, 
                                             initial_stocks, if_eval=True)

# Agent
agent = AgentPPO() # AgentSAC(), AgentTD3(), AgentDDPG()
agent.if_off_policy = False
args = Arguments(env, agent)
```

**Comment by zywang624** [comment]
We have changed the 'if_on_policy' to the 'if_on_policy' flag. Please use 'if_off_policy'.

**Comment by franklo79** [comment]
Thank you!, your help has been very useful
