### ISSUE TITLE
AgentDQN select_actions has typo of state

### ISSUE THREAD

**Issue by lingweizhu** [AI4Finance-Foundation/ElegantRL#59]
Hi,

I recently found ElegantRL and has been testing it. It seems there are some minor typos in the code such as the in the `AgentDQN` class. Its `select_actions` method has argument `states` but at line 274 it has the assignment `action = self.act(state.to(self.device))`, this causes the bug I am facing.

**Comment by zywang624** [comment]
Corrected this typo, thank you for your reminder.
