### ISSUE TITLE
Hello, can't find the module. What's the reason for this problem?

### ISSUE THREAD

**Issue by AlwaysStayHumble** [AI4Finance-Foundation/ElegantRL#63]
![image](https://user-images.githubusercontent.com/50932956/141951420-cb6fcaee-86fe-4b09-a796-4e6dcd55c7c8.png)

**Comment by everssun** [comment]
It has been changed to "save_or_load_model", and there is some place to be changed.

**Comment by AlwaysStayHumble** [comment]
thank you！
