### ISSUE TITLE
ModuleNotFoundError: No module named 'elegantrl.run'

### ISSUE THREAD

**Issue by nnfx-davis** [AI4Finance-Foundation/ElegantRL#68]
Trying to run the sample notebook from https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159 in Colab.

FinRL_PaperTrading_Demo.ipynb

from elegantrl.run import *

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-53-1f98d3692ca8> in <module>()
      2 import threading
      3 from finrl.neo_finrl.data_processors.processor_alpaca import AlpacaProcessor
----> 4 from elegantrl.run import *
      5 import alpaca_trade_api as tradeapi
      6 import time

ModuleNotFoundError: No module named 'elegantrl.run'

**Comment by Waterkin** [comment]
I also have this issue. Maybe it is the same as No module named 'elegantrl.agent' . And this one is because they change agent.py to agents.py ...
