### ISSUE TITLE
  ERROR: Failed building wheel for box2d-py; need to add swig to list of project requirements

### ISSUE THREAD

**Issue by t-b-r** [AI4Finance-Foundation/ElegantRL#73]
From https://github.com/openai/spinningup/issues/32, as per [this comment](https://github.com/openai/spinningup/issues/32#issuecomment-438968445), swig needs to be installed to build environments from source in cases where the pre-built version is not compatible with the user's system.

**Comment by supersglzc** [comment]
Thanks for your comment, we will update it soon.
