### ISSUE TITLE
Possible wrong inherit in AgentMADDPG

### ISSUE THREAD

**Issue by FredHJC** [AI4Finance-Foundation/ElegantRL#84]
<img width="1405" alt="截屏2021-12-16 下午9 27 26" src="https://user-images.githubusercontent.com/24794992/146478937-afbd3eac-4c72-4c77-9d54-b9a0aad2cac4.png">

The import is trying to inherit from the AgentBase module, not the AgentBase class. This will throw a 
`TypeError: module() takes at most 2 arguments (3 given)
`

**Comment by FredHJC** [comment]
Also, the init() function is confusing. Why not including gamma as an arg? The current code will generate an error wherever this module is called using code developed for other modules, which has a gamma as an arg.

**Comment by shixun404** [comment]
MARL modules will be refactored this weekend, please wait a moment.

**Comment by shixun404** [comment]
AgentMADDPG inherits the previous version of AgentBase. We added the MADDPG demo in elegantrl_helloworld.
