### ISSUE TITLE
Wrong import, inconsistent Module/Class names, and other bugs in AgentQmix.py

### ISSUE THREAD

**Issue by FredHJC** [AI4Finance-Foundation/ElegantRL#85]
<img width="1302" alt="截屏2021-12-16 下午9 49 33" src="https://user-images.githubusercontent.com/24794992/146480834-379acc3d-69e9-4e80-be82-54ab925c11dc.png">

1) The Class name is not consistent with previous ones.
2) Wrong import. This one shall work
`from .net import VDN,QMix
`
3) This module will throw the following error
<img width="702" alt="截屏2021-12-16 下午9 50 43" src="https://user-images.githubusercontent.com/24794992/146480948-b0f787b2-fd2d-46c2-9b2b-c379d54077de.png">

**Comment by shixun404** [comment]
MARL modules will be refactored this weekend, please wait a moment

**Comment by shixun404** [comment]
I add Q-Mix demo in elegantrl_helloworld:

- Install SMAC first:
 `cd elegantrl/envs/SMAC`
 `bash installsc2.sh`
 `pip install -r sc2_requirements.txt`
- Run an experiment:
`cd elegantrl_helloworld`
`python eRL_demo_QMIXinSingleFile.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z`
